version: '2.0'

services:
  drupal:
    image: drupal:latest
    ports:
      - 8000:80
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
    restart: always

  mysql:
    image: mariadb:latest
    expose:
      - "3306"
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db_dump:/dump
      # All .sql files will be imported on first start by order.
      - ./database/mysql-init:/docker-entrypoint-initdb.d
      - ./config/mysql:/etc/mysql:ro
    restart: always

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
  db_dump:
